{% set name = "ansible-base" %}
{% set version = "2.10.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33ae323923b841f3d822f355380ce7c92610440362efeed67b4b39db41e555af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - cryptography
    - jinja2
    - packaging
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - pyyaml

test:
  imports:
    - ansible
    - ansible._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - mariusvniekerk
