{% set name = "ansible-base" %}
{% set version = "2.10.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b15fa8b2dcfa613d2e7bfc8ec6524b1094d50ed29613b1fcc27237c017fe8d40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - cryptography
    - jinja2
    - packaging
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - pyyaml

test:
  imports:
    - ansible
    - ansible._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - mariusvniekerk
